theme: minima

title: Tackling unnecessary Complexities...

description: 'there are too much work needs to be done; remember the motto of Pivotal Labs: "Do the right thing; do what works; be kind"'

twitter_username: gigiyyjp

author: Guixin

email: guixin.zhu@yahoo.com
