theme: minima

title: Tackling unnecessary Complexities...

description: 'there are too much work needs to be done; just remember the motto of Pivotal Labs: "Do the right thing; do what works; be kind"'

github_username: gigiyy

author: Guixin

email: guixin.zhu@yahoo.com
